import { ArrowRight } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Eyebrow, PageHero, Photo, Reveal, SectionTitle } from "./atoms";
import { images, people } from "@/data/site";
import logo from "@/assets/logo-seal.jpg";

const wrap = "mx-auto max-w-7xl px-5 sm:px-8";
const section = "py-20 lg:py-28";

export function AboutPage() {
  const milestones = [["2003", "SAIT is formed as the student association of the new IT division."], ["2011", "The annual technical festival expands to welcome colleges across Kerala."], ["2018", "Student project labs and peer-led skill circles become weekly fixtures."], ["2026", "A renewed SAIT brings community, careers and creative technology under one roof."]];
  const resources = ["Academic calendar", "Course handbook", "Lab guidelines", "Student support"];
  return <>
    <PageHero label="About SAIT" title="Twenty-three years of learning together." text="The student voice of the Division of Information Technology—connecting academic life with practical curiosity, friendship and opportunity."/>
    <Reveal className={`${section} ${wrap}`}><div className="grid gap-12 lg:grid-cols-12"><div className="flex flex-col items-start gap-8 lg:col-span-5"><SectionTitle eyebrow="Our purpose" title="Community is our operating system." copy="SAIT connects the Department of Information Technology with the student experience beyond the classroom."/><img src={logo} alt="Students Association of Information Technology official seal" className="size-44 rounded-full object-cover shadow-soft"/></div><div className="grid gap-5 sm:grid-cols-2 lg:col-span-7"><article className="about-value rounded-[1.75rem] bg-secondary p-8"><Eyebrow>Vision</Eyebrow><h3 className="font-display text-2xl">Confidence to create responsibly.</h3><p className="mt-4 leading-7 text-muted-foreground">Every IT student leaves CUSAT with the confidence, community and curiosity to create responsibly.</p></article><article className="about-value rounded-[1.75rem] bg-olive p-8 text-primary-foreground"><Eyebrow>Mission</Eyebrow><h3 className="font-display text-2xl">Learning made shared.</h3><p className="mt-4 leading-7 text-primary-foreground/70">Create accessible spaces for peer learning, experimentation, leadership and meaningful industry exchange.</p></article></div></div></Reveal>
    <Reveal className="bg-secondary py-20"><div className={wrap}><SectionTitle eyebrow="History" title="Small beginnings. Lasting momentum."/><div className="about-timeline border-l border-gold pl-7">{milestones.map(([year, text]) => <article className="relative pb-10 last:pb-0" key={year}><span className="absolute -left-[2.05rem] top-1 size-3 rounded-full bg-gold"/><p className="font-display text-3xl text-olive">{year}</p><p className="mt-2 max-w-2xl leading-7 text-muted-foreground">{text}</p></article>)}</div></div></Reveal>
    <Reveal className={`${section} ${wrap}`}><div className="grid gap-12 lg:grid-cols-2"><Photo src={images.campus} alt="CUSAT campus" className="aspect-[4/3]"/><div><SectionTitle eyebrow="Division of IT" title="Rigorous academics, with room to explore." copy="The Division of Information Technology at the School of Engineering supports undergraduate and postgraduate learning across software systems, data, networks and emerging technologies."/><h3 className="font-display text-2xl">Faculty coordinators</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{people.slice(0, 2).map(person => <article className="about-faculty rounded-2xl border border-border p-5" key={person.name}><strong className="block break-words">{person.name}</strong><p className="mt-1 text-sm text-muted-foreground">{person.role}</p></article>)}</div></div></div></Reveal>
    <Reveal className="bg-primary py-20 text-primary-foreground"><div className={wrap}><SectionTitle light eyebrow="Quick access" title="Academic resources"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{resources.map(resource => <a href="#" onClick={event => event.preventDefault()} key={resource} className="about-resource flex items-center justify-between rounded-2xl border border-primary-foreground/15 p-5 transition-colors duration-200 hover:bg-primary-foreground/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{resource}<ArrowRight/></a>)}</div></div></Reveal>
  </>;
}
