import { useState, type FormEvent } from "react";
import { Mail, MapPin, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Eyebrow, InteractiveGrid, PageHero, Reveal, SectionTitle } from "./atoms";

const wrap = "mx-auto max-w-7xl px-5 sm:px-8";
const section = "py-20 lg:py-28";

export function ContactPage() {
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  return <>
    <PageHero label="Contact" title="Come say hello." text="Questions, ideas or a collaboration in mind? The SAIT room and inbox are both open."/>
    <Reveal className={`${section} ${wrap}`}><div className="grid gap-8 lg:grid-cols-12"><div className="lg:col-span-5"><SectionTitle eyebrow="Find us" title="On campus, at the heart of SOE."/><div className="contact-details space-y-5 text-sm"><p><strong className="block">Department</strong><span className="text-muted-foreground">Division of Information Technology, School of Engineering</span></p><p><strong className="block">Location</strong><span className="text-muted-foreground">CUSAT, Thrikkakara, Kochi, Kerala 682022</span></p><p><strong className="block">Email</strong><a className="mt-1 inline-flex items-center gap-2 text-olive transition-colors hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" href="mailto:hello@saitcusat.example"><Mail className="size-4"/>hello@saitcusat.example</a></p></div><div className="relative mt-10 aspect-[16/10] overflow-hidden rounded-[1.75rem] bg-secondary"><InteractiveGrid className="pointer-events-none absolute inset-0 pattern-grid opacity-55"/><div className="absolute inset-0 grid place-items-center"><div className="rounded-full bg-primary p-4 text-primary-foreground shadow-medium"><MapPin/></div></div><span className="absolute bottom-5 left-5 rounded-full bg-background px-4 py-2 text-xs font-semibold shadow-soft">School of Engineering · CUSAT</span></div></div><form onSubmit={submit} className="contact-form rounded-[1.75rem] bg-secondary p-6 sm:p-9 lg:col-span-7"><div className="flex items-start justify-between gap-4"><div><Eyebrow>Send a note</Eyebrow><h2 className="font-display text-3xl">Start a conversation</h2><p className="mt-2 text-sm text-muted-foreground">We’ll route your note to the right SAIT team.</p></div><Send className="mt-1 text-olive" aria-hidden="true"/></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold" htmlFor="contact-name">Name *<Input id="contact-name" required className="mt-2 h-12 bg-background"/></label><label className="text-sm font-semibold" htmlFor="contact-email">Email *<Input id="contact-email" required type="email" className="mt-2 h-12 bg-background"/></label><label className="text-sm font-semibold sm:col-span-2" htmlFor="contact-subject">Subject *<Input id="contact-subject" required className="mt-2 h-12 bg-background"/></label><label className="text-sm font-semibold sm:col-span-2" htmlFor="contact-message">Message *<Textarea id="contact-message" required className="mt-2 min-h-36 bg-background"/></label></div><Button type="submit" variant="gold" className="mt-6">Send message <Send/></Button>{sent && <p className="mt-4 flex items-center gap-2 text-sm text-olive" role="status">Thanks—we’ll get back to you soon.</p>}</form></div></Reveal>
    <Reveal className="bg-secondary py-20"><div className={wrap}><SectionTitle eyebrow="Quick answers" title="Frequently asked"/><div className="grid gap-4 md:grid-cols-3">{[["Can any IT student join?", "Yes. SAIT activities are open across batches and experience levels."], ["Can I propose an event?", "Absolutely. Share the idea through the contact form or visit the SAIT room."], ["Are events free?", "Most campus events are free. Any fee is always shown clearly before registration."]].map(([question, answer]) => <article className="contact-faq rounded-[1.5rem] bg-background p-6" key={question}><h3 className="font-display text-lg">{question}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{answer}</p></article>)}</div></div></Reveal>
  </>;
}
